Start git synchronizer tool
LUMC/git-mirrorer pull request #1
Opened 2019-04-12 12:45 UTC by rhpvorderman

2019-04-29 12:55 UTC, DavyCats requested changes

2019-04-29 12:55 UTC, DavyCats commented on README.md
> +Git-synchronizer fetches al branches and tags from the main repository and pushes them to the mirror repositories.
```suggestion
Git-synchronizer fetches all branches and tags from the main repository and pushes them to the mirror repositories.
```

2019-04-29 12:55 UTC, DavyCats commented on README.md
> +Git-synchronizer is optimized to work in a cron job. Main and mirror repo’s are set using a config file. Git-synchronizer supports fetching and pushing multiple repositories at once.
```suggestion
Git-synchronizer is optimized to work in a cron job. Main and mirror repos are set using a config file. Git-synchronizer supports fetching and pushing multiple repositories at once.
```

2019-04-29 12:55 UTC, DavyCats commented on docs/index.rst
> +Git-synchronizer fetches al branches and tags from the main repository and
```suggestion
Git-synchronizer fetches all branches and tags from the main repository and
```

2019-04-29 12:55 UTC, DavyCats commented on docs/index.rst
> +Git-synchronizer is optimized to work in a cron job. Main and mirror repo's are
```suggestion
Git-synchronizer is optimized to work in a cron job. Main and mirror repos are
```

2019-04-29 12:55 UTC, DavyCats commented on src/git_synchronizer/git_synchronizer.py
> +        # Allows is to store errors during processing
```suggestion
        # Allows storing errors during processing
```
or 
```suggestion
        # This is to store errors during processing
```
?

2019-04-29 12:55 UTC, DavyCats commented on src/git_synchronizer/git_synchronizer.py
> +                        help="how many git operations will be performed at "
```suggestion
                        help="The number of git operations which will be performed at "
```

2019-04-29 12:55 UTC, DavyCats commented on src/git_synchronizer/git_synchronizer.py
> +                             "should be at least 1.")
Should these be ssh urls or https?

2019-04-29 13:09 UTC, sndrtj requested changes

2019-04-29 13:09 UTC, sndrtj commented on setup.py
> +    version="0.1-dev",
not semantically versioned?

2019-04-29 13:09 UTC, sndrtj commented on src/git_synchronizer/git_synchronizer.py
> +        if self.repo_dir.exists():
you don't have to do the reassignment of `self.repo`. I.e. the following obviates line 43.

```python
if self.repo_dir.exists():
    self.repo = git.Repo(path=self.repo_dir)
else:
    self.repo = None
```

2019-04-29 13:09 UTC, sndrtj commented on src/git_synchronizer/git_synchronizer.py
> +        """Mirrors the repo from the main git url to the miror git urls"""
this is going to give errors in case `self.repo` is None. In that case `self.clone()` will return None, but `self.fetch()` will fail with an `AttributeError`. 

This begets the question, why is `self.repo` allowed to be None in the first place?

2019-04-29 13:09 UTC, sndrtj commented on src/git_synchronizer/git_synchronizer.py
> +class RepoQueue(queue.Queue):
This feels all a bit overengineered. A simple for loop is not sufficient, because?

2019-04-29 13:09 UTC, sndrtj commented on src/git_synchronizer/git_synchronizer.py
> +    with config.open('rt') as config_h:
Mode `t` is implicit from `r`.

2019-04-29 13:09 UTC, sndrtj commented on src/git_synchronizer/git_synchronizer.py
> +        clean_line = line.strip(os.linesep)
I think the same can be achieved using `line.rstrip()`, or perhaps even with simply `line.strip()` if you need to strip from both ends.

2019-04-29 13:46 UTC, rhpvorderman commented on src/git_synchronizer/git_synchronizer.py
> +        """Mirrors the repo from the main git url to the miror git urls"""
So the cloning (which is time consuming) can take place in a separate thread.

2019-04-29 13:46 UTC, rhpvorderman commented on src/git_synchronizer/git_synchronizer.py
> +        """Mirrors the repo from the main git url to the miror git urls"""
Unfortunately gitpython interacts only directly with existing git directories. Not with not yet cloned ones

2019-04-29 13:47 UTC, rhpvorderman commented on src/git_synchronizer/git_synchronizer.py
> +class RepoQueue(queue.Queue):
That does not scale well with lots of repos, because web requests are slow. And we plan to mirror lots of them and run this at regular intervals..

2019-04-29 13:48 UTC, rhpvorderman commented on src/git_synchronizer/git_synchronizer.py
> +    with config.open('rt') as config_h:
explicit is better than implicit :wink:

2019-04-29 13:48 UTC, rhpvorderman commented on src/git_synchronizer/git_synchronizer.py
> +        clean_line = line.strip(os.linesep)
:+1: great suggestion.

2019-04-30 09:45 UTC, sndrtj approved these changes

2019-04-30 10:02 UTC, merged